apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: portfolio-route
spec:
  parentRefs:
  - name: my-gateway
    namespace: traefik
  hostnames:
  - "viniciuscaol.online"
  rules:
  - backendRefs:
    - name: portfolio-service
      port: 80